name: wafrahtest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1   # For Firebase Authentication
  cloud_functions: ^5.1.3  # For Firebase Cloud Functions
  http: ^1.2.2
  webview_flutter: ^4.9.0
  cloud_firestore: ^5.4.4
  lean_sdk_flutter: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  

